version: "3.8"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --backend-store-uri /mlflow/mlruns --host 0.0.0.0 --port 5000

  streamlit:
    build: ./app
    container_name: mlops_steamlit
    ports: 
      - "8501:8501"
    depends_on:
      - mlflow
    volumes:
      - ./app:/app